import time

from ST7735 import TFT

from machine import SPI, Pin

from ST7735 import TFT


spi = SPI(2, baudrate=2000000, polarity=0, phase=0, sck=Pin(16), mosi=Pin(15))
tft = TFT(spi, 41, 42, 45)
tft.initr()
tft.rgb(True)


class st7735(object):
    def d_1():
        tft.pixel((12, 119), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((13, 121), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((14, 114), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((15, 113), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((16, 114), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((18, 110), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((19, 106), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((20, 108), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((21, 106), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((22, 103), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((23, 100), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((24, 94), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((25, 90), TFT.WHITE)

        tft.pixel((25, 90), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((27, 92), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((29, 88), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((28, 88), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((29, 85), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((31, 84), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((32, 86), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((34, 84), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((34, 83), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((35, 80), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((36, 82), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((38, 83), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((39, 80), TFT.WHITE)

        tft.pixel((40, 80), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((42, 81), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((44, 80), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((46, 79), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((48, 78), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((50, 79), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((52, 78), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((53, 76), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((55, 77), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((57, 76), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((58, 75), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((60, 74), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((61, 75), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((62, 72), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((63, 73), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((65, 72), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((67, 71), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((69, 70), TFT.WHITE)
        time.sleep_ms(10)

    def d_2():
        tft.pixel((10, 115), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((11, 117), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((12, 114), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((13, 110), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((15, 103), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((16, 105), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((17, 100), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((19, 94), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((20, 91), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((21, 85), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((22, 80), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((23, 76), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((25, 71), TFT.WHITE)
        time.sleep_ms(10)

        tft.pixel((26, 70), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((27, 66), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((28, 68), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((29, 64), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((30, 67), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((31, 66), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((32, 64), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((33, 63), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((34, 62), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((35, 61), TFT.WHITE)
        time.sleep_ms(10)

        tft.pixel((41, 62), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((43, 61), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((45, 59), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((47, 60), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((48, 61), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((50, 58), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((51, 56), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((52, 58), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((54, 57), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((56, 55), TFT.WHITE)
        time.sleep_ms(1)
        tft.pixel((58, 56), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((60, 54), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((62, 54), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((64, 53), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((66, 52), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((69, 51), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((70, 52), TFT.WHITE)
        time.sleep_ms(10)

    def d_3():
        tft.pixel((11, 120), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((12, 110), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((13, 105), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((15, 90), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((17, 85), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((18, 77), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((19, 75), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((20, 73), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((21, 70), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((22, 67), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((23, 64), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((25, 62), TFT.WHITE)
        time.sleep_ms(10)

        tft.pixel((25, 63), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((27, 62), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((28, 60), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((29, 58), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((30, 55), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((31, 57), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((32, 56), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((33, 55), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((35, 56), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((36, 53), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((37, 52), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((38, 54), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((39, 51), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((40, 50), TFT.WHITE)
        time.sleep_ms(10)

        tft.pixel((42, 50), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((44, 49), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((46, 48), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((48, 49), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((50, 48), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((51, 46), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((53, 47), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((55, 46), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((57, 45), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((59, 44), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((60, 43), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((62, 42), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((63, 41), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((64, 39), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((66, 40), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((68, 40), TFT.WHITE)
        time.sleep_ms(10)
        tft.pixel((70, 38), TFT.WHITE)
        time.sleep_ms(10)

